
services:
  # Laravel Application Service: The main PHP application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: softvence/pulse_backend_laravel:latest
    platform: linux/amd64
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "8000:8000" # Exposes the application on port 8000
    env_file:
      - .env
    volumes:
      - app_public_storage:/var/www/html/storage/app/public # Persists storage
    networks:
      - laravel

  # Laravel Queue Worker Service: Processes background jobs
  queue:
    image: softvence/pulse_backend_laravel:latest
    platform: linux/amd64
    container_name: laravel_queue
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    env_file:
      - .env
    volumes:
      - app_public_storage:/var/www/html/storage/app/public
    depends_on:
      app:
        condition: service_started
    networks:
      - laravel

networks:
  laravel:
    driver: bridge # Creates a custom bridge network

volumes:
  app_public_storage:
    driver: local

